# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "052b6779f6dc229c35cf123ce5617276"
name = "te-entrego"
handle = "te-entrego-0"
application_url = "https://israeli-powell-brochures-mechanical.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-85b53c2a.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders"

[auth]
redirect_urls = [
  "https://israeli-powell-brochures-mechanical.trycloudflare.com/auth/callback",
  "https://israeli-powell-brochures-mechanical.trycloudflare.com/auth/shopify/callback",
  "https://israeli-powell-brochures-mechanical.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
